### ISSUE TITLE
dude this is the equivalent of using a json file as a db

### ISSUE THREAD

**Issue by asterized** [Sas2k/ToyBase#1]

**Comment by Sas2k** [comment]
Yeah, this is just a Toy Database just to display/experiment on the way a Database works. Nothing serious

**Comment by Sas2k** [comment]
Also the .tb file is a pickled .csv file you could say.

**Comment by Sas2k** [comment]
also since this is issue is un-active I'm just going to close it. If you have any doubt or etc... Open another issue.
